project_id = "eplxmeedcrbrmzlvqjxe"

[functions.generate-plan]
verify_jwt = false

[functions.calendar-ics]
verify_jwt = false

[functions.send-notification-emails]
verify_jwt = false

[functions.explain-task]
verify_jwt = false

[functions.get-shared-plan]
verify_jwt = false

[functions.share-plan-email]
verify_jwt = false

[functions.get-shared-calendar]
verify_jwt = false

[functions.generate-bp-charts]
verify_jwt = false

[functions.generate-business-model]
verify_jwt = false

[functions.get-shared-business-model]
verify_jwt = false
